name: Checks

on:
  push:
    branches:
      - "master"

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G
