name: Checks

on:
  push:
    branches:
      - "master"

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: curl, dom, mbstring, libxml, zip, pcntl, pdo, pdo_mysql
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug
      - name: Install dependencies & prepare Laravel
        run: |
          composer install --no-interaction --no-progress
          cp .env.example .env
          php artisan key:generate
          php artisan route:cache
      - name: Create Extra Databases
        env:
          MYSQL_HOST: "127.0.0.1"
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
        run: bash ./docker/database/create-testing-database.sh
      - name: Run PHPUnit
        env:
          DB_HOST: "127.0.0.1"
        run: php artisan test --coverage --min=80

